### ISSUE TITLE
DoNote Share!: Meta

### ISSUE THREAD

**Issue by startergate** [startergate/DoNote#1]
Share Function Must Be Included in v0.4-beta.
This is To Do List.
This is Meta Issue. There Will Be More Issue.
- [x] 1) Database Configuration.
- [x] 2) Share Pages
   - [x] 1. Shared Page List
   - [x] 2. Shared Page View / Edit
   - [x] 3. Remove Shared
   - [x] 4. Share Start
   - [x] 5. Share Code Add
- [x] 3) Share Functions
   - [x] 1. Shared Page Edit
   - [x] 2. Remove Shared
   - [x] 3. Share Start
   - [x] 4. Share Stop
   - [x] 5. Add Shared Page
- [x] 4) E-Mail Sending Function (Canceled)

**Comment by startergate** [comment]
Stage 1 Completed!(2018.5.17 UI Fix Commit)

**Comment by startergate** [comment]
Shared Page List Created(2018.5.23 Share List Update)
